In [25]:
import numpy as np

# Define the size of the array
n_rows = 4
n_cols = 10

def L2(p1,p2):
    if isinstance(p1, np.ndarray) and isinstance(p2, np.ndarray):
        p1x,p1y = p1.flatten()
        p2x,p2y = p2.flatten()
        return np.sqrt((p2x-p1x)**2 + (p2y-p1y)**2)
    else: # either point is 0
        return 100

# Define the scalar and vector values for the rows
A = np.zeros((4,10), dtype=object)
A[0] = np.random.randint(low=1, high=4, size=(1, n_cols))
for i in range(10):
    A[1][i] = np.random.rand(1, 2)
    A[2][i] = np.random.rand(1, 2)
    A[3][i] = np.random.rand(1, 2) # Each row in the 4th row has a vector of length 2
for j in [0,3,4]:
    A[1][j] = 0
    A[3][j] = 0
print("Array A:\n", A)

Array A:
 [[3 3 3 2 3 1 2 1 2 3]
 [0 array([[0.90431758, 0.70099336]]) array([[0.62923146, 0.95118296]]) 0
  0 array([[0.32030244, 0.63761496]]) array([[0.01838428, 0.44548588]])
  array([[0.07017718, 0.21690105]]) array([[0.45987113, 0.48830663]])
  array([[0.08717271, 0.62287743]])]
 [array([[0.58146544, 0.55900254]]) array([[0.30739277, 0.83514573]])
  array([[0.66141378, 0.84571127]]) array([[0.18271309, 0.26741878]])
  array([[0.58002812, 0.70974526]]) array([[0.61629364, 0.09383648]])
  array([[0.12328802, 0.63471766]]) array([[0.46882101, 0.22047695]])
  array([[0.74048907, 0.64843968]]) array([[0.40493506, 0.33191187]])]
 [0 array([[0.92689327, 0.10571232]]) array([[0.93769685, 0.83911358]]) 0
  0 array([[0.82408464, 0.06952347]]) array([[0.37776766, 0.50043352]])
  array([[0.50759056, 0.51614389]]) array([[0.1459957, 0.399875 ]])
  array([[0.39933139, 0.77526501]])]]


In [30]:
epsilon =0.5
for i in range(A.shape[1]):
    for j in range(i + 1, A.shape[1]):
        if L2(A[3, i], A[3, j]) < epsilon:
            print(i,j)


1 5
6 7
6 8
6 9
7 8
7 9
8 9


In [27]:
# Define the threshold epsilon
epsilon = 10

# Find columns that satisfy the conditions
valid_cols = np.where(
    ((A[0] == 1) | (A[0] == 2))
    & np.array([isinstance(element, np.ndarray) for element in A[1]])
    & np.array([isinstance(element, np.ndarray) for element in A[2]])
    & ~np.any([
        L2(A[3, i], A[3, j]) < epsilon
        for i in range(A.shape[1])
        for j in range(i + 1, A.shape[1])
    ])
    )[0]

print("Valid columns:", valid_cols)

Valid columns: []


In [ ]:
# Define the threshold epsilon
epsilon = 10

# Find columns that satisfy the conditions
valid_cols = np.where(
    ((A[0] == 1) | (A[0] == 2))
    & np.array([isinstance(element, np.ndarray) for element in A[1]])
    & np.array([isinstance(element, np.ndarray) for element in A[2]])
    )[0]

print("Valid columns:", valid_cols)

In [21]:
set_indx = set()
for i in valid_cols:
    for j in valid_cols:
        set_indx.add((i,j))
print(len(set_indx))

0


In [22]:
# Iterate over valid columns and check L2 norm for corresponding elements in A[3]
for idx in valid_cols:
    if isinstance(A[3][idx], np.ndarray) and L2([0, 0], A[3][idx]) < epsilon:
        print(f"A[3][{idx}] passes the condition")
    else:
        print(f"A[3][{idx}] fails the condition")